$(document).ready(function(){
    $('video').click(function(){
        if($(this).get(0).paused){
            $(this).get(0).play();
        }else{
            $(this).get(0).pause();
        }
    });
});